name: github-actions-env-actions-workflow
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # /home/runner/work/github-actions-env/github-actions-env
      - run: echo ${{ github.workspace }} 
      
      # /home/runner/work/github-actions-env/github-actions-env
      - run: echo $GITHUB_WORKSPACE
     
